version: "3.11"

services:

  flask:
    container_name: flask
    hostname: app
    build: ./flask
    expose:
      - 8080
    ports:
     - "8080:5000"
    environment:
      - TZ=Asia/Taipei

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - flask